services:
- type: web
  name: placement-predictor
  env: python
  buildCommand: "pip install -r requirements.txt"
  startCommand: "python api.py"
  envVars:
  - key: FLASK_ENV
    value: production
  - key: PORT
    value: "5000"
